[package]
name = "flying"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
hostname = "0.4.2"
mdns-sd = "0.17.1"
petname = "2.0.2"
rand = "0.9.2"
sha2 = "0.10.9"
tokio = { version = "1.48.0", features = ["full"] }
