[package]
name = "flying"
version = "3.1.0"
edition = "2024"

repository = "https://github.com/wpcRaskolnikov/flying.git"

[dependencies]
aes-gcm = "0.10.3"
clap = { version = "4.5.53", features = ["derive"] }
hostname = "0.4.2"
mdns-sd = "0.17.1"
petname = "2.0.2"
rand = "0.9.2"
sha2 = "0.10.9"
socket2 = "0.6.1"
tokio = { version = "1.48.0", features = ["full"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
